site_name: b3Faraz-springboot
nav:
  - Intoduction: 'index.md'
  - Configs:
      - Getting started: 'getting-started.md' 
      - Installation:
          - Prerequisites: 'prerequisites.md'
  - About: 'about.md'
docs_dir: docs
plugins:
  - techdocs-core
